export { default as AmbientLight} from './svelt3/AmbientLight.svelte'
export { default as Group } from './svelt3/Group.svelte'
export { default as Axes } from './svelt3/Axes.svelte'
export { default as Mesh } from './svelt3/Mesh.svelte'
export { default as MeshBasicMaterial } from './svelt3/MeshBasicMaterial.svelte'
export { default as MeshStandardMaterial } from './svelt3/MeshStandardMaterial.svelte'
export { default as PointLight } from './svelt3/PointLight.svelte'
export { default as SpotLight } from './svelt3/SpotLight.svelte'
export { default as Svelt3 } from './svelt3/S3d.svelte'

export {default as Demo } from './demo/App.svelte'